DEFAULT_CHUNK_SIZE = 512
DEFAULT_CHUNK_OVERLAP = 100
DEFAULT_TOP_K = 3
DEFAULT_DISTANCE_THRESHOLD = 0.5
DEFAULT_EMBEDDING_MODEL = "publishers/google/models/textembedding-gecko"
DEFAULT_EMBEDDING_REQUESTS_PER_MIN = 1000
PROJECT_ID="fabled-badge-458903-t9"
LOCATION = "us-central1"